package com.javainuse.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;

import com.javainuse.repository.ReviewRepository;
import com.javainuse.model.Review;

@Controller // This means that this class is a Controller
@RequestMapping(path="/review") // This means URL's start with /demo (after Application path)
public class ReviewController {
  @Autowired // This means to get the bean called userRepository
         // Which is auto-generated by Spring, we will use it to handle the data
  private ReviewRepository reviewRepository;

  @CrossOrigin(origins = "*")
  @PostMapping(path="/add/{id}") // Map ONLY POST Requests
  public @ResponseBody String addReview(
    @PathVariable(value = "id") Integer id,
    @RequestBody Review review
  ) {
    Review r = new Review();
    r.setIdBook(id);
    r.setReview(review.getReview());
    reviewRepository.save(r);
    return "Saved";

  }

  @CrossOrigin(origins = "*")
  @GetMapping(path="/all/{id}")
  public @ResponseBody Iterable<Review> getAllReviews(
    @PathVariable(value = "id") Integer id
  ) {
    // This returns a JSON or XML with the users
    return reviewRepository.findByIdBook(id);
  }
}